SELECT (SELECT 
SUM(CASE WHEN(b.th_akademik = ts2.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_dosen ELSE 0 END) AS a_biaya_dosen_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_tenaga_kependidikan ELSE 0 END) AS a_biaya_tenaga_kependidikan_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_operasional_pembelajaran ELSE 0 END) AS a_biaya_operasional_pembelajaran_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_operasional_tidak_langsung ELSE 0 END) AS a_biaya_operasional_tidak_langsung_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_operasional_kemahasiswaan ELSE 0 END) AS a_biaya_operasional_kemahasiswaan_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_penelitian ELSE 0 END) AS a_biaya_penelitian_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_pkm ELSE 0 END) AS a_biaya_pkm_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_investasi_sdm ELSE 0 END) AS a_biaya_investasi_sdm_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_investasi_sarana ELSE 0 END) AS a_biaya_investasi_sarana_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_investasi_prasarana ELSE 0 END) AS a_biaya_investasi_prasarana_ts2,
SUM(CASE WHEN(b.th_akademik = ts1.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_dosen ELSE 0 END) AS a_biaya_dosen_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_tenaga_kependidikan ELSE 0 END) AS a_biaya_tenaga_kependidikan_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_operasional_pembelajaran ELSE 0 END) AS a_biaya_operasional_pembelajaran_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_operasional_tidak_langsung ELSE 0 END) AS a_biaya_operasional_tidak_langsung_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_operasional_kemahasiswaan ELSE 0 END) AS a_biaya_operasional_kemahasiswaan_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_penelitian ELSE 0 END) AS a_biaya_penelitian_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_pkm ELSE 0 END) AS a_biaya_pkm_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_investasi_sdm ELSE 0 END) AS a_biaya_investasi_sdm_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_investasi_sarana ELSE 0 END) AS a_biaya_investasi_sarana_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_investasi_prasarana ELSE 0 END) AS a_biaya_investasi_prasarana_ts1,
SUM(CASE WHEN(b.th_akademik = ts.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_dosen ELSE 0 END) AS a_biaya_dosen_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_tenaga_kependidikan ELSE 0 END) AS a_biaya_tenaga_kependidikan_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_operasional_pembelajaran ELSE 0 END) AS a_biaya_operasional_pembelajaran_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_operasional_tidak_langsung ELSE 0 END) AS a_biaya_operasional_tidak_langsung_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_operasional_kemahasiswaan ELSE 0 END) AS a_biaya_operasional_kemahasiswaan_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_penelitian ELSE 0 END) AS a_biaya_penelitian_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_pkm ELSE 0 END) AS a_biaya_pkm_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_investasi_sdm ELSE 0 END) AS a_biaya_investasi_sdm_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_investasi_sarana ELSE 0 END) AS a_biaya_investasi_sarana_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun AND b.prodi='TEKNIK INDUSTRI S1') THEN biaya_investasi_prasarana ELSE 0 END) AS a_biaya_investasi_prasarana_ts,
'' AS b_biaya_dosen_ts2, 
'' AS b_biaya_tenaga_kependidikan_ts2, 
'' AS b_biaya_operasional_pembelajaran_ts2, 
'' AS b_biaya_operasional_tidak_langsung_ts2, 
'' AS b_biaya_operasional_kemahasiswaan_ts2, 
'' AS b_biaya_penelitian_ts2, 
'' AS b_biaya_pkm_ts2, 
'' AS b_biaya_investasi_sdm_ts2, 
'' AS b_biaya_investasi_sarana_ts2, 
'' AS b_biaya_investasi_prasarana_ts2,
'' AS b_biaya_dosen_ts1, 
'' AS b_biaya_tenaga_kependidikan_ts1, 
'' AS b_biaya_operasional_pembelajaran_ts1, 
'' AS b_biaya_operasional_tidak_langsung_ts1, 
'' AS b_biaya_operasional_kemahasiswaan_ts1, 
'' AS b_biaya_penelitian_ts1, 
'' AS b_biaya_pkm_ts1, 
'' AS b_biaya_investasi_sdm_ts1, 
'' AS b_biaya_investasi_sarana_ts1, 
'' AS b_biaya_investasi_prasarana_ts1,
'' AS b_biaya_dosen_ts, 
'' AS b_biaya_tenaga_kependidikan_ts, 
'' AS b_biaya_operasional_pembelajaran_ts, 
'' AS b_biaya_operasional_tidak_langsung_ts, 
'' AS b_biaya_operasional_kemahasiswaan_ts, 
'' AS b_biaya_penelitian_ts, 
'' AS b_biaya_pkm_ts, 
'' AS b_biaya_investasi_sdm_ts, 
'' AS b_biaya_investasi_sarana_ts, 
'' AS b_biaya_investasi_prasarana_ts
FROM dana_prodi b
LEFT JOIN ts AS ts2 ON ts2.tahun = b.th_akademik AND ts2.prodi = 'TEKNIK INDUSTRI S1' AND ts2.nama_ts = 'TS-2' 
LEFT JOIN ts AS ts1 ON ts1.tahun = b.th_akademik AND ts1.prodi = 'TEKNIK INDUSTRI S1' AND ts1.nama_ts = 'TS-1' 
LEFT JOIN ts ON ts.tahun = b.th_akademik AND ts.prodi = 'TEKNIK INDUSTRI S1' AND ts.nama_ts = 'TS' 

UNION ALL

SELECT 
'' AS a_biaya_dosen_ts2, 
'' AS a_biaya_tenaga_kependidikan_ts2, 
'' AS a_biaya_operasional_pembelajaran_ts2, 
'' AS a_biaya_operasional_tidak_langsung_ts2, 
'' AS a_biaya_operasional_kemahasiswaan_ts2, 
'' AS a_biaya_penelitian_ts2, 
'' AS a_biaya_pkm_ts2, 
'' AS a_biaya_investasi_sdm_ts2, 
'' AS a_biaya_investasi_sarana_ts2, 
'' AS a_biaya_investasi_prasarana_ts2,
'' AS a_biaya_dosen_ts1, 
'' AS a_biaya_tenaga_kependidikan_ts1, 
'' AS a_biaya_operasional_pembelajaran_ts1, 
'' AS a_biaya_operasional_tidak_langsung_ts1, 
'' AS a_biaya_operasional_kemahasiswaan_ts1, 
'' AS a_biaya_penelitian_ts1, 
'' AS a_biaya_pkm_ts1, 
'' AS a_biaya_investasi_sdm_ts1, 
'' AS a_biaya_investasi_sarana_ts1, 
'' AS a_biaya_investasi_prasarana_ts1,
'' AS a_biaya_dosen_ts, 
'' AS a_biaya_tenaga_kependidikan_ts, 
'' AS a_biaya_operasional_pembelajaran_ts, 
'' AS a_biaya_operasional_tidak_langsung_ts, 
'' AS a_biaya_operasional_kemahasiswaan_ts, 
'' AS a_biaya_penelitian_ts, 
'' AS a_biaya_pkm_ts, 
'' AS a_biaya_investasi_sdm_ts, 
'' AS a_biaya_investasi_sarana_ts, 
'' AS a_biaya_investasi_prasarana_ts,
SUM(CASE WHEN(b.th_akademik = ts2.tahun) THEN biaya_dosen ELSE 0 END) AS b_biaya_dosen_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun) THEN biaya_tenaga_kependidikan ELSE 0 END) AS b_biaya_tenaga_kependidikan_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun) THEN biaya_operasional_pembelajaran ELSE 0 END) AS b_biaya_operasional_pembelajaran_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun) THEN biaya_operasional_tidak_langsung ELSE 0 END) AS b_biaya_operasional_tidak_langsung_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun) THEN biaya_operasional_kemahasiswaan ELSE 0 END) AS b_biaya_operasional_kemahasiswaan_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun) THEN biaya_penelitian ELSE 0 END) AS b_biaya_penelitian_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun) THEN biaya_pkm ELSE 0 END) AS b_biaya_pkm_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun) THEN biaya_investasi_sdm ELSE 0 END) AS b_biaya_investasi_sdm_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun) THEN biaya_investasi_sarana ELSE 0 END) AS b_biaya_investasi_sarana_ts2, 
SUM(CASE WHEN(b.th_akademik = ts2.tahun) THEN biaya_investasi_prasarana ELSE 0 END) AS b_biaya_investasi_prasarana_ts2,
SUM(CASE WHEN(b.th_akademik = ts1.tahun) THEN biaya_dosen ELSE 0 END) AS b_biaya_dosen_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun) THEN biaya_tenaga_kependidikan ELSE 0 END) AS b_biaya_tenaga_kependidikan_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun) THEN biaya_operasional_pembelajaran ELSE 0 END) AS b_biaya_operasional_pembelajaran_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun) THEN biaya_operasional_tidak_langsung ELSE 0 END) AS b_biaya_operasional_tidak_langsung_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun) THEN biaya_operasional_kemahasiswaan ELSE 0 END) AS b_biaya_operasional_kemahasiswaan_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun) THEN biaya_penelitian ELSE 0 END) AS b_biaya_penelitian_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun) THEN biaya_pkm ELSE 0 END) AS b_biaya_pkm_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun) THEN biaya_investasi_sdm ELSE 0 END) AS b_biaya_investasi_sdm_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun) THEN biaya_investasi_sarana ELSE 0 END) AS b_biaya_investasi_sarana_ts1, 
SUM(CASE WHEN(b.th_akademik = ts1.tahun) THEN biaya_investasi_prasarana ELSE 0 END) AS b_biaya_investasi_prasarana_ts1,
SUM(CASE WHEN(b.th_akademik = ts.tahun) THEN biaya_dosen ELSE 0 END) AS b_biaya_dosen_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun) THEN biaya_tenaga_kependidikan ELSE 0 END) AS b_biaya_tenaga_kependidikan_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun) THEN biaya_operasional_pembelajaran ELSE 0 END) AS b_biaya_operasional_pembelajaran_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun) THEN biaya_operasional_tidak_langsung ELSE 0 END) AS b_biaya_operasional_tidak_langsung_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun) THEN biaya_operasional_kemahasiswaan ELSE 0 END) AS b_biaya_operasional_kemahasiswaan_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun) THEN biaya_penelitian ELSE 0 END) AS b_biaya_penelitian_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun) THEN biaya_pkm ELSE 0 END) AS b_biaya_pkm_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun) THEN biaya_investasi_sdm ELSE 0 END) AS b_biaya_investasi_sdm_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun) THEN biaya_investasi_sarana ELSE 0 END) AS b_biaya_investasi_sarana_ts, 
SUM(CASE WHEN(b.th_akademik = ts.tahun) THEN biaya_investasi_prasarana ELSE 0 END) AS b_biaya_investasi_prasarana_ts
FROM dana_fakultas b
LEFT JOIN ts AS ts2 ON ts2.tahun = b.th_akademik AND ts2.nama_ts = 'TS-2' 
LEFT JOIN ts AS ts1 ON ts1.tahun = b.th_akademik AND ts1.nama_ts = 'TS-1' 
LEFT JOIN ts ON ts.tahun = b.th_akademik AND ts.nama_ts = 'TS' 
) x